import Brands from "@/components/Brands";
import CategoriesSection from "@/components/CategoriesSection";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>E-commerce | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo/logo-light-streamline.png" />
      </Head>

      <Header />
      <HeroSection />
      <CategoriesSection />
      <Brands />
      <Footer />
    </>
  );
}
